### ISSUE TITLE
Error when running buildscript - gzip: stdin: not in gzip format

### ISSUE THREAD

**Issue by SangNguyen2601** [mathinstitut/goemaxima#14] opened 2023-09-07 08:23 UTC
Currently, I got an error when I try to create a goemaxima image

 > [ 4/12] RUN bash /buildscript.sh:
346.9 SBCL has been installed:
346.9  binary /usr/local/bin/sbcl
346.9  core and contribs in /usr/local/lib/sbcl/
346.9 
346.9 Documentation:
346.9  man /usr/local/share/man/man1/sbcl.1
346.9 
346.9 gzip: stdin: not in gzip format
346.9 tar: Child returned status 1
346.9 tar: Error is not recoverable: exiting now
#ERROR: process "/bin/sh -c bash /buildscript.sh" did not complete successfully: exit code: 2

Can everyone help me to identify why the buildscript throw this error?

SBCL Lisp version = 2.2.6
Maxima version = 5.41.0
StackMaximaVersion = 2023060500

**Update**:
After investigating, I think we got this error because it cannot get the Maxima source from Sourceforge
`wget "https://sourceforge.net/projects/maxima/files/Maxima-source/${MAXIMA_VERSION}-source/maxima-${MAXIMA_VERSION}.tar.gz"`
That make the tar command cannot unzip the file
`tar -xf maxima-${MAXIMA_VERSION}.tar.gz`

**Comment by Lennart-Kramer** [comment] 2023-09-07 14:31
The downloaded file currently has the following content:
```
<html><head>
<title>SourceForge</title>
<!-- <script src="/js/jquery.com/jquery-1.11.0.min.js"></script> -->
<script src="https://code.jquery.com/jquery-1.11.0.min.js"></script>
<script src="https://sourceforge.net/js/mirrors.js"></script>
<script src="/js/sf.js"></script>
<script>
var DR_loc = DR_parse_hash_url();
if (DR_loc) {
    DR_sf_main(DR_loc);
} else {
    window.location.href = 'https://sourceforge.net/home.html';
}
</script>
<meta name="description" content="Free, secure and fast downloads from the largest Open Source applications and software directory - SourceForge.net"/>
</head><body>
<noscript>
We're sorry -- the Sourceforge site is currently in Disaster Recovery mode.  Please check back later.
</noscript>
</body></html>
```
The error message only being inside noscript tags seems somewhat strange, but in any case maybe it's resolved in a few days... We've had issues with sourceforge in the past. Edit: I also seem to be unable to download the file through a browser.
Is there something preventing you from using the containers from dockerhub in the meantime?

Edit: Here's the status from sourceforge: https://fosstodon.org/@sourceforgestatus/111022248071061762

**Comment by SangNguyen2601** [comment] 2023-09-08 03:21
Yes, Lennart. However, I have a work around to pass this case, just a trick :)
So we just wait for this issue fixed on sourceforge, right? In my opinion, a suggestion that can we fetch the maxima code from github instead of sourceforge, will prevent this issue in the future.

**Comment by Lennart-Kramer** [comment] 2023-09-30 12:36
Just a small status update on this issue: I have tried setting up a maxima mirror on github (https://github.com/mathinstitut/maxima-mirror), however for older maxima versions it doesn't work right now so I haven't switched over.
The problem is that the git itself doesn't contain the generated autotools files (they are only contained within the release tars), but when attempting to generate them for older versions, the resulting build fails. I suspect it's because I'm using a newer autotools version that doesn't silently ignore an encoding error in one of the files that was ignored in an older version.
I think what I'm going to do is to mirror recent release tars with github releases and then make a script that automatically mirrors new release files as well.

**Closed as completed** 2023-10-31 19:01 UTC

**Comment by Lennart-Kramer** [comment] 2023-10-31 19:02
I made a cronjob that uploads new sourceforge releases to github releases and the buildscript now fetches from the github mirror.
